### ISSUE TITLE
Widget crashes on API 30+

### ISSUE THREAD

**Issue by hirame-tech** [hirame-tech/memodown#1]
Error contents in API 31
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.memodown, PID: 10622
    java.lang.RuntimeException: Unable to start receiver com.example.memodown.NewAppWidget: java.lang.IllegalArgumentException: com.example.memodown: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4317)
        at android.app.ActivityThread.access$1600(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.IllegalArgumentException: com.example.memodown: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.example.memodown.NewAppWidget.updateAppWidget(NewAppWidget.java:88)
        at com.example.memodown.NewAppWidget.onUpdate(NewAppWidget.java:122)
        at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4308)
        	... 9 more
```

**Comment by hirame-tech** [comment]
Corresponding part L88
```
final PendingIntent pendingUpdate=PendingIntent.getBroadcast(context, appWidgetId, intentUpdate, PendingIntent.FLAG_UPDATE_CURRENT);
```

**Comment by hirame-tech** [comment]
I changed it as below so,  It worked in API 31 but,  didn't work in API 33
```
final PendingIntent pendingUpdate=PendingIntent.getBroadcast(context, appWidgetId, intentUpdate, PendingIntent.FLAG_IMMUTABLE);
```

**Comment by hirame-tech** [comment]
After upgrating Android Studio, It worked.
